<script setup>

</script>

<template>
  <main>
    <section class="hero">
      <h1>No Limits</h1>
      <video autoplay muted>
        <source src="../assets/atlas-card.webm" type="video/mp4" />
      </video>
      <article>
        This is your friend who scores the hottest tables in town, your passport to weekend
        getaways, and your guest pass to must-see events. All brilliantly brought together in a card
        and app of uncompromising beauty and utility. This is the beginning of a journey to a world
        with no limits.
      </article>
      <p>This is Atlas.</p>
    </section>
      

  </main>

  <footer>
    <div>
      <ol>
        <li>
          ATLAS SUPPER CLUB RESERVATIONS ARE AVAILABLE ON A FIRST COME, FIRST SERVE BASIS
          EXCLUSIVELY TO ATLAS CARDHOLDERS FROM WITHIN ATLAS APP. THE ATLAS SUPPER CLUB CODE OF
          CONDUCT <a href="">(ATLASCARD.COM/CODE-OF-CONDUCT)</a> AND THE CANCELLATION POLICY OF THE
          APPLICABLE RESTAURANT APPLY FOR EACH RESERVATION. LISTED RESTAURANTS ARE SUBJECT TO CHANGE
          AT ANY TIME WITHOUT PRIOR NOTICE.
        </li>
        <li>LAST-MINUTE RESERVATIONS SUBJECT TO AVAILABILITY.</li>
        <li>
          5X POINTS WITH BLADE APPLIES TO ALL ELIGIBLE BLADE SERVICES. 5X POINTS IS CALCULATED AND
          APPLIED AT THE END OF STATEMENT PERIODS THAT INCLUDE SETTLED BLADE TRANSACTIONS.
        </li>
        <li>
          PROVIDED AS A $189 STATEMENT CREDIT TO YOUR ATLAS ACCOUNT UPON PURCHASE OF CLEAR PLUS
          ANNUAL MEMBERSHIP WITH YOUR ATLAS CARD. VISIT <a href="">ENROLL.CLEARME.COM/ENROLL/</a> TO
          LEARN MORE.
        </li>
        <li>
          ATLAS CARDHOLDERS ARE ELIGIBLE TO RECEIVE REIMBURSEMENT FOR UP TO $600 PER YEAR OF
          CANCELLATION/CHANGE FEE INCURRED WITH RESPECT TO ELIGIBLE AIRFARE PURCHASES THAT ARE
          CANCELED FOR ANY REASON, FOR WHICH REIMBURSEMENT IS SOUGHT BEFORE THE BENEFIT END DATE,
          AND IF THE ELIGIBLE CARDHOLDER IS NOT ELIGIBLE TO RECEIVE A REIMBURSEMENT FROM ANOTHER
          SOURCE.
        </li>
        <li>VISIT <a href="">HTTPS://ATLASCARD.COM/VISA-INFINITE</a> TO LEARN MORE.</li>
        <li>YOUR PHYSICAL CARD DETAILS ARE AVAILABLE TO ACCESS ANY TIME WITHIN ATLAS APP.</li>
        <li>
          REWARDED CATEGORIES ELIGIBLE FOR 3X POINTS UPGRADE INCLUDE DINING, FLIGHTS, HOTELS,
          RIDESHARES, NIGHTLIFE, FASHION, GROCERIES, WELLNESS, HEALTH, HOME, AND AUTO SERVICES. 3X
          POINTS UPGRADE IS CALCULATED AND APPLIED AT THE END OF EACH STATEMENT PERIOD ON SETTLED
          TRANSACTIONS WITHIN YOUR TOP REWARDED CATEGORY BY DOLLAR AMOUNT. OUTSIDE OF THE TOP SPEND
          CATEGORY, SETTLED TRANSACTIONS FOR PRODUCTS AND SERVICES PROVIDED BY MERCHANTS AND/OR
          CATEGORIES NOT SUBJECT TO ANOTHER POINTS MULTIPLIER, WILL ACCRUE 1 POINT FOR EVERY DOLLAR
          SPENT (1X POINTS) AFTER THE APPLICABLE BILLING CYCLE. SUBJECT TO RESTRICTIONS AND THE
          REWARDS & BENEFIT TERMS.
        </li>
        <li>
          CREATE UNLIMITED NEW CARDS WITHIN ATLAS APP, WITH UP TO FIVE ACTIVE CARDS AT ANY ONE TIME.
        </li>
        <li>
          CARDHOLDER IS RESPONSIBLE FOR THE COST OF PURCHASES OF GOODS AND SERVICES AND/OR THIRD
          PARTY EXPENSES AND SERVICES INCURRED IN RELATION TO ANY FULFILLED REQUESTS.
        </li>
        <li>
          PROVIDED AS A $199 STATEMENT CREDIT TO YOUR ATLAS ACCOUNT UPON PURCHASE OF ONE MEDICAL
          ANNUAL MEMBERSHIP WITH YOUR ATLAS CARD. VISIT <a href="">ONEMEDICAL.COM/ATLAS/</a> TO
          LEARN MORE.
        </li>
        <li>
          COMPLIMENTARY $100 ANNUAL EREWHON CAFE MEMBERSHIP. BENEFIT ENROLLMENT INSTRUCTIONS
          PROVIDED IN APP.
        </li>
        <li>
          UP TO $300 IN ANNUAL STATEMENT CREDITS ($25/MONTH). GET YOUR FIRST MONTH FREE BY USING THE
          FUTURE FITNESS ATLAS CARDHOLDER ENROLLMENT PAGE. VISIT
          <a href="">FUTURE.CO/ATLASCARD</a> TO LEARN MORE.
        </li>
        <li>
          ATLAS IS A TRUE CHARGE CARD WITH NO PRE-SET SPENDING LIMITS. THIS MEANS YOUR SPENDING
          LIMIT IS FLEXIBLE. UNLIKE TRADITIONAL CARDS WITH SET LIMITS, THE AMOUNT YOU CAN SPEND
          FLEXIBLY ADAPTS BASED ON A RANGE OF FACTORS SUCH AS YOUR PURCHASES, STATEMENT BALANCE
          PAYMENTS, AND CREDIT HISTORY.
        </li>
      </ol>
    </div>
  </footer>
</template>
